// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxsttajrlxchoebxshca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4c3R0YWpybHhjaG9lYnhzaGNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1NDU4MzQsImV4cCI6MjA1MTEyMTgzNH0.EHEgyiohv8zYceO81tyXigcfIueFYCqp2qmc2LpJ6OI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);